@Library('odf-aar-library') _

pipeline {
    agent {
        docker {
            image 'quay.io/powercloud/inbound-agent:4.6-1.5'
            args '-v /etc/resolv.conf:/etc/resolv.conf'
            label 'jump-vpc-x86_64'
        }
    }
    parameters {
        string(defaultValue: '', description: 'OCP version on which OCS/ODF will be deployed', name: 'ocpVersion')
        string(defaultValue: '', description: 'OCS version which you want to upgrade', name: 'ocsVersion')
        string(defaultValue: '', description: 'rhceph-dev/ocs-registry Image used for deploying OCS/ODF', name: 'ocsRegistryImage')
        string(defaultValue: '', description: 'OCS version in which you want to upgrade', name: 'ocsUpgradeVersion')
        string(defaultValue: '', description: 'rhceph-dev/ocs-registry image of upgraded ocs version', name: 'ocsUpgradeRegistryImage')
        string(defaultValue: '720', description: 'Enter time(in Minutes) to retain the cluster', name: 'KeepFor')       
    }
    environment {
        //users and credentials. All must be defined in Jenkins Credentials
        GITHUB_USER = credentials('GITHUB_USER')
        IBMCLOUD_API_KEY = credentials('AAR_IBMCLOUD_API_KEY')
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
        REDHAT_USERNAME = credentials('REDHAT_USERNAME')
        REDHAT_PASSWORD = credentials('REDHAT_PASSWORD')
        PULL_SECRET = credentials('ODF_PULL_SECRET')
        ODF_AUTH = credentials('ODF_AUTH_FILE')

        //Env constants
        TERRAFORM_VER = "1.2.0"

        IBM_CLOUD_REGION = "lon"
        IBM_CLOUD_ZONE = "lon06"
        SERVICE_INSTANCE_ID = "fac4755e-8aff-45f5-8d5c-1d3b58b7a229"

        //Makefile variables
        OPENSHIFT_POWERVS_GIT_TF_DEPLOY_BRANCH="master" //The download branch

        TARGET = "deploy-openshift4-powervs-odf"
        TEMPLATE_FILE = ".${TARGET}.tfvars.template"
        POWERVS = true
        SCRIPT_DEPLOYMENT = false
        WAIT_FOR_DEBUG = "1"

        // Type of configuration
        CONFIG_TYPE="min"
       
        // Parameters
        OCP_RELEASE = "${params.ocpVersion}"
        ODF_VERSION = "${params.ocsVersion}"
        UPGRADE_OCS_VERSION = "${params.ocsUpgradeVersion}"
        OCS_REGISTRY_IMAGE = "${params.ocsRegistryImage}"
        UPGRADE_OCS_REGISTRY = "${params.ocsUpgradeRegistryImage}"
        TIMEOUT = "${params.KeepFor}"

        // ODF Variables
        PLATFORM = "powervs"
        //ODF_VERSION = "4.11"
        ENABLE_FIPS = false
        ENABLE_VAULT = false
        // OCS_REGISTRY_IMAGE="quay.io/rhceph-dev/ocs-registry:latest-stable-4.11.0"
        TIER_TEST_SUITE = "1"
	
    }
    
    stages {
        stage('Clone ansible extra') {
            steps {
                cloneRepo("git@github.ibm.com:redstack-power/ocp4_ansible_extras.git", "ansible_extra")
            }
        }
        stage('Setting RHCOS and RHEL Images as per OCP version') {
            steps {
                script {
                    switch (env.OCP_RELEASE) {
                case "4.6":
                            env.BASTION_IMAGE = "rhel-83"
                            env.RHCOS_IMAGE = "rhcos-46"
                            break
                case "4.7":
                            env.BASTION_IMAGE = "rhel-83"
                            env.RHCOS_IMAGE = "rhcos-47"
                            break
                case "4.8":
                            env.BASTION_IMAGE = "rhel-83"
                            env.RHCOS_IMAGE = "rhcos-48"
                            break
                case "4.9":
                            env.BASTION_IMAGE = "rhel-84"
                            env.RHCOS_IMAGE = "rhcos-49"
                            break
                case "4.10":
                            env.BASTION_IMAGE = "rhel-84"
                            env.RHCOS_IMAGE = "rhcos-410"
                            break
                case "4.11":
                            env.BASTION_IMAGE = "rhel-85"
                            env.RHCOS_IMAGE = "rhcos-411"
                            break
                default:
                     env.BASTION_IMAGE = "rhel-86"
                            env.RHCOS_IMAGE = "rhcos-412"
                    }
            
                    env.BASTION_IMAGE_FILE = "latest-${BASTION_IMAGE}-rdr-svenkat-ocp-storage-lon06-odf-411.txt"
                    env.RHCOS_IMAGE_FILE = "latest-${RHCOS_IMAGE}-rdr-svenkat-ocp-storage-lon06-odf-411.txt"
                }
            }
        }
        stage('Setup Common Environment Variables') {
            steps {
                setupCommonEnvironmentVariablesOdf()
                authYamlOdf()
                setupClusterConfigOdf("${CONFIG_TYPE}")
                script {
                    env.SYSTEM_TYPE = "e980"
                }
            }
        }
        stage('pull artifact') {
            steps {
                getArtifacts("mirror-openshift-release", "latest-${OCP_RELEASE}-build.txt" )
                getArtifacts("powervs/odf-testing-aar/poll-powervs-images", "${BASTION_IMAGE_FILE}")
                getArtifacts("powervs/odf-testing-aar/poll-powervs-images", "${RHCOS_IMAGE_FILE}" )
            }
        }
        //Checkout the installer git repo
        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                        pullSecretOdf()
                        env.OPENSHIFT_IMAGE = ""
                        env.OCP_RELEASE_TAG = ""
                        if (fileExists("deploy/artifactory/latest-${OCP_RELEASE}-build.txt")) {
                            env.OPENSHIFT_IMAGE = readFile "deploy/artifactory/latest-${OCP_RELEASE}-build.txt"
                            env.OPENSHIFT_IMAGE = env.OPENSHIFT_IMAGE.trim()
                            env.OCP_RELEASE_TAG = env.OPENSHIFT_IMAGE.split(":")[1].trim()
                        }
                        else {
                            echo "latest-${OCP_RELEASE}-build.txt file does not exist. Please check mirror-openshift-release job"
                            throw err
                        }
                        if (fileExists("deploy/artifactory/${BASTION_IMAGE_FILE}")) {
                            env.BASTION_IMAGE_NAME = readFile "deploy/artifactory/${BASTION_IMAGE_FILE}"
                            env.BASTION_IMAGE_NAME = env.BASTION_IMAGE_NAME.trim()
                        }
                        else{
                            echo "${BASTION_IMAGE_FILE} file does not exist. Please check poll-powervs-job"
                            throw err
                        }
                        if (fileExists("deploy/artifactory/${RHCOS_IMAGE_FILE}")) {
                            env.RHCOS_IMAGE_NAME = readFile "deploy/artifactory/${RHCOS_IMAGE_FILE}"
                            env.RHCOS_IMAGE_NAME = env.RHCOS_IMAGE_NAME.trim()
                        }
                        else{
                            echo "${RHCOS_IMAGE_FILE} file does not exist. Please check poll-powervs-job"
                            throw err
                        }
                    }
                    catch (err)
                    {
                        echo 'Error ! Template preparation failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
        stage('Initialize Environment') {
            steps {
                initializeEnvironmentOdf()
            }
        }
        stage('Setup Terraform Plugin') {
            steps {
                setupTerraformPlugin()
            }
        }
        stage('Deploy OCP Cluster') {
            steps {
                deployCluster()
            }
        }
        
        stage('Setup Kubectl') {
            steps {
                setupKubeconfigOcp4()
            }
        }
        stage('Exporting ODF Environment Variables') {
            steps {
                odfUpgradeEnvironmentVariables()
            }
        }
        stage('Executing ODF Setup Script') {
            steps {
                odfSetupScript()
            }
        }
               
        stage('Deploying ODF') {
            steps {
                odfDeployScript()
            }
        }
        stage('Verifying ODF Resources') {
            steps {
                checkOdfResources()
            }
        }
        stage('Upgrading ODF to "${UPGRADE_OCS_VERSION}"') {
            steps {
                upgradeOdf()
            }
        }
        stage('Gathering ODF resources after Upgrade') {
            steps {
                script{
                    sed -i 's|odf-resources.log|odf-resources-upgrade.log|g' ${WORKSPACE}/scripts/check-odf-resources.sh
                }
                checkOdfResources()
            }
        }

        stage('Running tier1') {
            steps {
                executeTierTestsOdf()
            }
        }

        stage('Capture tier test summary after upgrading ODF') {
            steps {
                odfCaptureTierSummary()
            }
        }

        stage('Waiting to timeout') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        TIMEOUT_MIN = TIMEOUT.toInteger()
                        if ( TIMEOUT_MIN != 0 ){
                            TIMEOUT_SEC=TIMEOUT_MIN*60
                            echo "HOLDING THE CLUSTER TEAR DOWN FOR ${TIMEOUT_MIN} MINUTES"
                            sleep TIMEOUT_SEC
                        }
                    }
                    catch (err) {
                        echo 'Error ! Timeout stage failed!'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }   
    }
    post {
        always {
            archiveAllArtifacts("setup-ocs-ci.log", "deploy-ocs-ci.log", "odf-resources.log", "upgrade-ocs-ci.log", "odf-resources-upgrade.log",
                "test-ocs-ci-tier-${TIER_TEST_SUITE}.log")
            cleanupOcp4Cluster()
            checkInfraError()
            odfProcessTierTestResults()
            cleanupPowerVSResources()
            notifyBySlack(currentBuild.result, env.MESSAGE)
            cleanWs()
        }
    }
}
