@Library('odf-aar-library') _

pipeline {
    agent {
        docker {
            image 'quay.io/powercloud/inbound-agent:4.6-1.5'
            args '-v /etc/resolv.conf:/etc/resolv.conf'
            label 'jump-vpc-x86_64'
        }
    }
   
     environment {
        //users and credentials. All must be defined in Jenkins Credentials
        GITHUB_USER = credentials('GITHUB_USER')
        IBMCLOUD_API_KEY = credentials('AAR_IBMCLOUD_API_KEY')
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
        REDHAT_USERNAME = credentials('REDHAT_USERNAME')
        REDHAT_PASSWORD = credentials('REDHAT_PASSWORD')
        PULL_SECRET = credentials('ODF_PULL_SECRET')
        ODF_AUTH = credentials('ODF_AUTH_FILE')

        //Env constants
        TERRAFORM_VER = "1.2.0"

        IBM_CLOUD_REGION = "lon"
        IBM_CLOUD_ZONE = "lon06"
        SERVICE_INSTANCE_ID = "fac4755e-8aff-45f5-8d5c-1d3b58b7a229"

        BASTION_IMAGE = "rhel-85"
        RHCOS_IMAGE = "rhcos-411"
        BASTION_IMAGE_FILE = "latest-${BASTION_IMAGE}-rdr-svenkat-ocp-storage-lon06-odf-411.txt"
        RHCOS_IMAGE_FILE = "latest-${RHCOS_IMAGE}-rdr-svenkat-ocp-storage-lon06-odf-411.txt"
        OCP_RELEASE = "4.11"
        
        //Makefile variables
        OPENSHIFT_POWERVS_GIT_TF_DEPLOY_BRANCH="master" //The download branch

        TARGET = "deploy-openshift4-powervs-odf"
        TEMPLATE_FILE = ".${TARGET}.tfvars.template"
        POWERVS = true
        SCRIPT_DEPLOYMENT = false
        WAIT_FOR_DEBUG = "1"
        BASTION_IP = "158.176.147.109"

        // ODF Variables
        PLATFORM = "powervs"
        ODF_VERSION = "4.11"
        ENABLE_FIPS = false
        ENABLE_VAULT = false
       // OCS_REGISTRY_IMAGE="quay.io/rhceph-dev/ocs-registry:latest-stable-4.11.0"
	 }
    
    stages {
        stage('Setup Common Environment Variables') {
            steps {
                setupCommonEnvironmentVariablesOdf()
                pullSecretOdf()
                authYamlOdf()
            }
        }
        stage('pull Key artifacts') {
            steps {
                getArtifactsOdf("powervs/odf-testing-aar/odf-test-job/testing", "id_rsa" )
                getArtifactsOdf("powervs/odf-testing-aar/odf-test-job/testing", "id_rsa.pub" )
            }
        }
        stage('Prepare to Login') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                        
                        if (fileExists("deploy/id_rsa}")) {
                            //env.WORKSPACE = "/home/jenkins/workspace/powervs/odf-testing-aar/odf-deploy"
                            def private_file = readFile "deploy/id_rsa"
                            println(private_file)  > "$WORKSPACE/deploy/id_rsa"

                        }
                        else{
                            echo "id_rsa file does not exist. Please check odf-test-job"
                            throw err
                        }
                        if (fileExists("deploy/id_rsa.pub")) {
                            def public_file = readFile "deploy/id_rsa.pub"
                            println(public_file)  > "$WORKSPACE/deploy/id_rsa.pub"
                            
                        }
                        else{
                            echo "id_rsa.pub file does not exist. Please check odf_test_job"
                            throw err
                        }
                    }
                    catch (err)
                    {
                        echo 'Error ! Login to bastion preparation failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
        stage('Exporting ODF Environment Variables') {
            steps {
                exportOdfEnvironmentVariables()
            }
        }
        stage('Executing ODF Setup Script') {
            steps {
                odfSetupScript()
            }
        }
               
        stage('Deploying ODF') {
            steps {
                odfDeployScript()
            }
        }
        stage('Verifying ODF Resources') {
            steps {
                checkOdfResources()
            }
        }
        	    
    }
}

