language: python
sudo: required
dist: trusty

branches:
  only:
  - master

services:
  - docker

script:
  - make verify
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make load-jenkins-jobs; fi'
